server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikare:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximun-pool-size: 20
      minimun-idle: 10
      poo-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate: 
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
      "[hibernate.generate_statistics]": true
      "[hibernate.connection.provider_disables_autocommit]": true

