version: '3.7'

services:
  mysql:
    container_name: use_service_myslq
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=user_services
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - user_services_network

networks:
  user_services_network:
